name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement"]
  - title: "🐛 Bug Fixes"
    labels: ["bug", "fix"]
  - title: "🧹 Maintenance"
    labels: ["chore", "refactor"]
  - title: "💥 Breaking Changes"
    labels: ["major", "breaking change"]

change-template: "- $TITLE (#$NUMBER)"

template: |
  ## 📦 Release $RESOLVED_VERSION

  ## Changes
  $CHANGES

version-resolver:
  major:
    labels: ["major", "breaking change"]
  minor:
    labels: ["feature", "enhancement"]
  patch:
    labels: ["bug", "fix", "chore", "refactor"]
  default: patch