name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement"]
  - title: "🐛 Bug Fixes"
    labels: ["bug"]
  - title: "📝 Documentation"
    labels: ["documentation"]
  - title: "🧹 Refactoring"
    labels: ["refactor"]
  - title: "🔧 Maintenance"
    labels: ["chore"]
  - title: "📝 Other Changes"
    labels: []

change-template: "- $TITLE (#$NUMBER)"

template: |
  ## 📦 Release $RESOLVED_VERSION

  ## Changes
  $CHANGES
