name: Release Drafter

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    types: [opened, reopened, synchronize, closed, labeled, unlabeled]
    paths-ignore:
      - '.github/**'
      
permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}